---
- name: Common tasks FTW
  hosts: all
  become: yes
  pre_tasks:
    - name: Set hostname
      hostname: name={{inventory_hostname}}

- name: Set all services
  hosts: base
  become: yes
  roles:
    - { role: nodejs, tags: nodejs }
    - { role: gify-panda, tags: gify-panda }
    - { role: counter-panda, tags: counter-panda }
    - { role: appManager, tags: appManager }
