---
- name: copy counter-panda
  copy: src=counter-panda dest=/tmp/ owner=root group=root mode=0755
  register: serviceUpdated

- name: npm install
  npm: path=/tmp/counter-panda
  when: serviceUpdated.changed
